language: r
latex: false
dist: precise

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

install:
    - sudo apt-get install libgsl0-dev
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install_deps(dep = T)'