language: r
sudo: false
cache: packages
latex: false

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

install:
    - sudo apt-get install libgsl0-dev