language: r

sudo: required



cache: packages

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
   ./travis-tool.sh aptget_install libgsl0-dev